baseURL: https://sofaemha.github.io/docs
title: Dokumentasi
theme: docs
defaultContentLanguage : id
languageCode: id
disablePathToLower: true
enableGitInfo: true

markup:
  highlight:
    style: dracula
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1

languages:
  id:
    languageName: Indonesian
    contentDir: content
    weight: 1

menu:
  after:
    - name: GitHub
      url: https://github.com/sofaemha/
      weight: 1
    - name: License
      url: /license/
      weight: 2

params:
  BookTheme: "dark"
  BookToC: true
  BookSection: docs
  BookRepo: https://github.com/sofaemha/docs
  BookCommitPath: commit
  BookEditPath: edit/main
  BookSearch: true
  BookComments: false

permalinks:
  posts: /posts/:year/:month/:day/:title/